server:
  port: 11111
  tomcat:
    uri-encoding: UTF-8
    remote-ip-header: x-forwarded-for
  use-forward-headers: true


spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  application:
    name: nevermore
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://161.117.15.122:3306/nevermore?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&allowMultiQueries=true
    username: root
    password: fuck_hacker
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connection-init-sqls: set names utf8mb4;
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 10
      maxActive: 200
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # Druid WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico,/druid/*'
      # Druid StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
      # 配置日志输出
      filter:
        config:
          enabled: true
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          statement-executable-sql-log-enabled: true
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
  servlet:
    multipart:
      max-request-size: 300MB
      max-file-size: 300MB
#  resources:
#    static-locations: file://${nevermore.resource.dir}/
#  mvc:
#    static-path-pattern: /resources/**
  jackson:
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

nevermore:
  resourceHost: http://localhost:${server.port}/resources
  resource:
    dir: /Users/wuyingjie/wyj/nevermore/files
  files:
    video: /videos/
    image: /images/
    tmp: /tmps/
mybatis:
  configuration:
    map-underscore-to-camel-case: true # 将下划线转为 驼峰